language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
# command to run tests
script:
  - python main.py --folder test_data/CarlaExs/ --cov-report term --cov=app/test/
  - python main.py --folder test_data/OpenDriveExs/ --cov-report term --cov=app/test/
  
after_success:
  - codecov
